// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace cinemaXXX {
	
	
	public partial class admin_advanced {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.PlaceHolder PlaceHolderNavigation;
		
		protected System.Web.UI.WebControls.PlaceHolder PlaceHolderSelect;
		
		protected System.Web.UI.WebControls.PlaceHolder PlaceHolderEdit;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl advAdminButtons;
	}
}
