// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace cinemaXXX {
	
	
	public partial class create_user {
		
		protected System.Web.UI.WebControls.Content headContent;
		
		protected System.Web.UI.WebControls.Content ContentPlaceHolderContent;
		
		protected System.Web.UI.WebControls.PlaceHolder errors;
		
		protected System.Web.UI.WebControls.TextBox fname;
		
		protected System.Web.UI.WebControls.TextBox lname;
		
		protected System.Web.UI.WebControls.TextBox phone;
		
		protected System.Web.UI.WebControls.TextBox email;
		
		protected System.Web.UI.WebControls.TextBox human;
		
		protected System.Web.UI.WebControls.TextBox passwd;
		
		protected System.Web.UI.WebControls.TextBox passwdAgain;
		
		public new cinemaXXX.masterpage Master {
			get {
				return ((cinemaXXX.masterpage)(base.Master));
			}
		}
	}
}
