// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace cinemaXXX {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl showMovieStats;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl showMovieDesc;
		
		protected System.Web.UI.WebControls.Image showMovieImg;
	}
}
