// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace cinemaXXX {
	
	
	public partial class masterpage {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.WebControls.PlaceHolder loginBox;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl menu;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder;
	}
}
