// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace cinemaXXX {
	
	
	public partial class movie_prototype {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Literal debugtext;
		
		protected System.Web.UI.WebControls.PlaceHolder placeholder1;
		
		protected System.Web.UI.WebControls.Button clickmigbutton;
	}
}
